fix: TypeError when assigning `pipeline_state.x.pos[1]`
TypeError: JAX arrays are immutable and do not support in-place item assignment.
Instead of x[idx] = y, use x = x.at[idx].set(y) or another .at[] method:
https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.ndarray.at.html